import { existsSync, writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';
import { initGit } from '../parsers/git-parser.js';
import { getAllStrikes } from '../database/strike-log.js';
import { CATEGORY_RULES } from '../categorizer/rules.js';

const HOOK_START = '# STRIKE-LOGGER-HOOK-START';
const HOOK_END = '# STRIKE-LOGGER-HOOK-END';

/**
 * Get the bash hook script content
 */
function getHookScriptContent(): string {
  return `${HOOK_START}
# Automatically generated by @halonic/strike-logger. Do not edit manually.
if command -v strike-logger >/dev/null 2>&1; then
  strike-logger hook --check || exit 1
elif [ -f "./node_modules/.bin/strike-logger" ]; then
  ./node_modules/.bin/strike-logger hook --check || exit 1
else
  npx --no-install @halonic/strike-logger hook --check || exit 1
fi
${HOOK_END}`;
}

/**
 * Register pre-commit hook in local .git repository
 */
export async function registerPreCommitHook(targetDir: string = process.cwd()): Promise<boolean> {
  const gitDir = join(targetDir, '.git');
  if (!existsSync(gitDir)) {
    console.error(chalk.red('Error: Not a git repository or no .git folder found.'));
    return false;
  }

  const hooksDir = join(gitDir, 'hooks');
  const hookPath = join(hooksDir, 'pre-commit');
  const hookScript = getHookScriptContent();

  try {
    let existingContent = '';
    if (existsSync(hookPath)) {
      existingContent = readFileSync(hookPath, 'utf-8');
    }

    let newContent = '';
    const startIdx = existingContent.indexOf(HOOK_START);
    const endIdx = existingContent.indexOf(HOOK_END);

    if (startIdx !== -1 && endIdx !== -1 && startIdx < endIdx) {
      // Replace existing strike-logger hook block
      newContent = 
        existingContent.substring(0, startIdx) + 
        hookScript + 
        existingContent.substring(endIdx + HOOK_END.length);
    } else {
      // Append hook block
      if (existingContent.trim() === '') {
        newContent = '#!/bin/sh\n\n' + hookScript + '\n';
      } else {
        newContent = existingContent.trimEnd() + '\n\n' + hookScript + '\n';
      }
    }

    writeFileSync(hookPath, newContent, { mode: 0o755 });
    return true;
  } catch (error) {
    console.error(chalk.red('Failed to register git hook:'), error);
    return false;
  }
}

/**
 * Unregister pre-commit hook
 */
export async function unregisterPreCommitHook(targetDir: string = process.cwd()): Promise<boolean> {
  const hookPath = join(targetDir, '.git', 'hooks', 'pre-commit');
  if (!existsSync(hookPath)) {
    return true;
  }

  try {
    const existingContent = readFileSync(hookPath, 'utf-8');
    const startIdx = existingContent.indexOf(HOOK_START);
    const endIdx = existingContent.indexOf(HOOK_END);

    if (startIdx !== -1 && endIdx !== -1 && startIdx < endIdx) {
      let newContent = 
        existingContent.substring(0, startIdx) + 
        existingContent.substring(endIdx + HOOK_END.length);
      
      // Clean up empty hook file
      if (newContent.replace('#!/bin/sh', '').trim() === '') {
        newContent = '';
      }
      
      writeFileSync(hookPath, newContent, { mode: 0o755 });
    }
    return true;
  } catch (error) {
    console.error(chalk.red('Failed to unregister git hook:'), error);
    return false;
  }
}

/**
 * Scan git staged changes for active anti-patterns
 * @returns true if clean, false if any potential violations are detected
 */
export async function checkStagedChanges(
  dbPath?: string,
  repoPath: string = process.cwd()
): Promise<boolean> {
  try {
    const strikes = await getAllStrikes(dbPath);
    const activeStrikes = strikes.filter(s => !s.resolved);

    if (activeStrikes.length === 0) {
      return true; // No active strikes to guard against
    }

    const git = initGit(repoPath);
    // Get staged changes diff
    const stagedDiff = await git.diff(['--cached']);

    if (!stagedDiff || stagedDiff.trim() === '') {
      return true; // No staged changes
    }

    // Extract only added lines in diff
    const addedLines = stagedDiff
      .split('\n')
      .filter(line => line.startsWith('+') && !line.startsWith('+++'))
      .map(line => line.substring(1).trim());

    if (addedLines.length === 0) {
      return true;
    }

    const activeCategories = new Set(activeStrikes.map(s => s.category));
    const violations: { category: string; line: string; reason: string }[] = [];

    // Find rules for active strike categories
    const activeRules = CATEGORY_RULES.filter(rule => activeCategories.has(rule.category));

    for (const line of addedLines) {
      const lowerLine = line.toLowerCase();
      
      for (const rule of activeRules) {
        // Check pattern matches
        for (const pattern of rule.patterns) {
          if (pattern.test(lowerLine)) {
            violations.push({
              category: rule.category,
              line: line,
              reason: `Staged addition matches pattern: ${pattern.toString()}`
            });
            break;
          }
        }

        // Check keyword matches (requiring high confidence to reduce noise)
        // If the line contains at least two keywords of an active category, flag it
        const matchingKeywords = rule.keywords.filter(kw => lowerLine.includes(kw.toLowerCase()));
        if (matchingKeywords.length >= 2) {
          violations.push({
            category: rule.category,
            line: line,
            reason: `Staged addition contains category keywords: ${matchingKeywords.join(', ')}`
          });
        }
      }
    }

    if (violations.length > 0) {
      console.log('\n' + chalk.bold.yellow('⚠️  [STRIKE LOGGER] ANTI-PATTERN WARNING'));
      console.log(chalk.gray(`Detected potential recurring AI bugs in your staged changes.\n`));

      // Show top 5 violations to keep output readable
      violations.slice(0, 5).forEach((v, idx) => {
        console.log(chalk.red(`  [Violation ${idx + 1}] Category: ${v.category}`));
        console.log(chalk.gray(`    Line:   "${chalk.white(v.line.substring(0, 80))}"`));
        console.log(chalk.gray(`    Reason: ${v.reason}\n`));
      });

      if (violations.length > 5) {
        console.log(chalk.gray(`  ...and ${violations.length - 5} more violations.\n`));
      }

      console.log(chalk.bold.yellow('Action Required:'));
      console.log(chalk.gray('  • Review your code to ensure these errors are fixed.'));
      console.log(chalk.gray('  • To commit anyway, bypass with: git commit --no-verify'));
      console.log(chalk.gray('  • To resolve past strikes, mark them resolved in the database.\n'));

      return false; // Violations detected
    }

    return true; // Clean
  } catch (error) {
    console.error(chalk.red('Error during staged changes verification:'), error);
    return true; // Let the commit proceed on system error
  }
}
