import { existsSync, writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import chalk from 'chalk';
import { initGit, extractAddedLines } from '../parsers/git-parser.js';
import { getAllStrikes } from '../database/strike-log.js';
import { CATEGORY_RULES, CategoryRule } from '../categorizer/rules.js';
import type { Strike } from '../database/schema.js';

export interface Violation {
  category: string;
  line: string;
  reason: string;
}

/**
 * Scan a unified diff for lines that match the anti-pattern rules of the given
 * active strikes. Pure and side-effect free so it can be reused by the git hook
 * and the CI command (and unit tested).
 */
export function scanDiffForViolations(
  diff: string,
  activeStrikes: Strike[],
  rules: CategoryRule[] = CATEGORY_RULES
): Violation[] {
  if (!diff || diff.trim() === '' || activeStrikes.length === 0) {
    return [];
  }

  const addedLines = extractAddedLines(diff);
  if (addedLines.length === 0) return [];

  const activeCategories = new Set(activeStrikes.map((s) => s.category));
  const activeRules = rules.filter((rule) => activeCategories.has(rule.category));
  const violations: Violation[] = [];

  for (const line of addedLines) {
    const lowerLine = line.toLowerCase();

    for (const rule of activeRules) {
      let matched = false;

      for (const pattern of rule.patterns) {
        if (pattern.test(lowerLine)) {
          violations.push({
            category: String(rule.category),
            line,
            reason: `Staged addition matches pattern: ${pattern.toString()}`,
          });
          matched = true;
          break;
        }
      }

      // Require >= 2 keywords to reduce noise when no pattern matched.
      if (matched) continue;
      const matchingKeywords = rule.keywords.filter((kw) => lowerLine.includes(kw.toLowerCase()));
      if (matchingKeywords.length >= 2) {
        violations.push({
          category: String(rule.category),
          line,
          reason: `Staged addition contains category keywords: ${matchingKeywords.join(', ')}`,
        });
      }
    }
  }

  return violations;
}

/**
 * Pretty-print a list of violations to the console.
 */
export function printViolations(violations: Violation[], label = '[STRIKE LOGGER] ANTI-PATTERN WARNING'): void {
  console.log('\n' + chalk.bold.yellow(`⚠️  ${label}`));
  console.log(chalk.gray(`Detected ${violations.length} potential recurring AI bug(s) in the changes.\n`));

  violations.slice(0, 5).forEach((v, idx) => {
    console.log(chalk.red(`  [Violation ${idx + 1}] Category: ${v.category}`));
    console.log(chalk.gray(`    Line:   "${chalk.white(v.line.substring(0, 80))}"`));
    console.log(chalk.gray(`    Reason: ${v.reason}\n`));
  });

  if (violations.length > 5) {
    console.log(chalk.gray(`  ...and ${violations.length - 5} more violations.\n`));
  }
}

const HOOK_START = '# STRIKE-LOGGER-HOOK-START';
const HOOK_END = '# STRIKE-LOGGER-HOOK-END';

/**
 * Get the bash hook script content
 */
function getHookScriptContent(): string {
  return `${HOOK_START}
# Automatically generated by @halonic/strike-logger. Do not edit manually.
if command -v strike-logger >/dev/null 2>&1; then
  strike-logger hook --check || exit 1
elif [ -f "./node_modules/.bin/strike-logger" ]; then
  ./node_modules/.bin/strike-logger hook --check || exit 1
else
  npx --no-install @halonic/strike-logger hook --check || exit 1
fi
${HOOK_END}`;
}

/**
 * Register pre-commit hook in local .git repository
 */
export async function registerPreCommitHook(targetDir: string = process.cwd()): Promise<boolean> {
  const gitDir = join(targetDir, '.git');
  if (!existsSync(gitDir)) {
    console.error(chalk.red('Error: Not a git repository or no .git folder found.'));
    return false;
  }

  const hooksDir = join(gitDir, 'hooks');
  const hookPath = join(hooksDir, 'pre-commit');
  const hookScript = getHookScriptContent();

  try {
    let existingContent = '';
    if (existsSync(hookPath)) {
      existingContent = readFileSync(hookPath, 'utf-8');
    }

    let newContent = '';
    const startIdx = existingContent.indexOf(HOOK_START);
    const endIdx = existingContent.indexOf(HOOK_END);

    if (startIdx !== -1 && endIdx !== -1 && startIdx < endIdx) {
      // Replace existing strike-logger hook block
      newContent = 
        existingContent.substring(0, startIdx) + 
        hookScript + 
        existingContent.substring(endIdx + HOOK_END.length);
    } else {
      // Append hook block
      if (existingContent.trim() === '') {
        newContent = '#!/bin/sh\n\n' + hookScript + '\n';
      } else {
        newContent = existingContent.trimEnd() + '\n\n' + hookScript + '\n';
      }
    }

    writeFileSync(hookPath, newContent, { mode: 0o755 });
    return true;
  } catch (error) {
    console.error(chalk.red('Failed to register git hook:'), error);
    return false;
  }
}

/**
 * Unregister pre-commit hook
 */
export async function unregisterPreCommitHook(targetDir: string = process.cwd()): Promise<boolean> {
  const hookPath = join(targetDir, '.git', 'hooks', 'pre-commit');
  if (!existsSync(hookPath)) {
    return true;
  }

  try {
    const existingContent = readFileSync(hookPath, 'utf-8');
    const startIdx = existingContent.indexOf(HOOK_START);
    const endIdx = existingContent.indexOf(HOOK_END);

    if (startIdx !== -1 && endIdx !== -1 && startIdx < endIdx) {
      let newContent = 
        existingContent.substring(0, startIdx) + 
        existingContent.substring(endIdx + HOOK_END.length);
      
      // Clean up empty hook file
      if (newContent.replace('#!/bin/sh', '').trim() === '') {
        newContent = '';
      }
      
      writeFileSync(hookPath, newContent, { mode: 0o755 });
    }
    return true;
  } catch (error) {
    console.error(chalk.red('Failed to unregister git hook:'), error);
    return false;
  }
}

/**
 * Scan git staged changes for active anti-patterns
 * @returns true if clean, false if any potential violations are detected
 */
export async function checkStagedChanges(
  dbPath?: string,
  repoPath: string = process.cwd(),
  rules: CategoryRule[] = CATEGORY_RULES
): Promise<boolean> {
  try {
    const strikes = await getAllStrikes(dbPath);
    const activeStrikes = strikes.filter(s => !s.resolved);

    if (activeStrikes.length === 0) {
      return true; // No active strikes to guard against
    }

    const git = initGit(repoPath);
    // Get staged changes diff
    const stagedDiff = await git.diff(['--cached']);

    const violations = scanDiffForViolations(stagedDiff, activeStrikes, rules);

    if (violations.length > 0) {
      printViolations(violations);

      console.log(chalk.bold.yellow('Action Required:'));
      console.log(chalk.gray('  • Review your code to ensure these errors are fixed.'));
      console.log(chalk.gray('  • To commit anyway, bypass with: git commit --no-verify'));
      console.log(chalk.gray('  • To resolve past strikes, mark them resolved in the database.\n'));

      return false; // Violations detected
    }

    return true; // Clean
  } catch (error) {
    console.error(chalk.red('Error during staged changes verification:'), error);
    return true; // Let the commit proceed on system error
  }
}
