import { existsSync, mkdirSync } from 'fs';
import { writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import chalk from 'chalk';
import { getAllStrikes } from '../database/strike-log.js';
import { getRangeDiff } from '../parsers/git-parser.js';
import { scanDiffForViolations, printViolations } from '../hooks/hook-manager.js';
import { CATEGORY_RULES, CategoryRule } from '../categorizer/rules.js';

export const WORKFLOW_PATH = '.github/workflows/strike-logger.yml';

/**
 * Generate a GitHub Actions workflow that runs the strike-logger anti-pattern
 * check against the diff of a pull request.
 */
export function generateWorkflow(): string {
  return `# Auto-generated by @halonic/strike-logger.
# Fails a PR when it reintroduces a known, unresolved anti-pattern.
# Note: requires your strike database (data/strikes.json) to be committed.
name: Strike Logger

on:
  pull_request:
    branches: [main, master]

jobs:
  anti-pattern-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run strike-logger anti-pattern check
        run: npx --yes @halonic/strike-logger ci --check --base origin/\${{ github.base_ref }} --head HEAD
`;
}

/**
 * Write the CI workflow file into the target directory, creating the
 * `.github/workflows` directory if necessary.
 * @returns the relative path written, or null if it already existed and force is false.
 */
export async function writeWorkflowFile(
  targetDir: string = process.cwd(),
  force = false
): Promise<string | null> {
  const filePath = join(targetDir, WORKFLOW_PATH);
  if (existsSync(filePath) && !force) {
    return null;
  }

  const dir = dirname(filePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  await writeFile(filePath, generateWorkflow(), 'utf-8');
  return WORKFLOW_PATH;
}

export interface CiCheckOptions {
  base: string;
  head?: string;
  dbPath?: string;
  repoPath?: string;
  rules?: CategoryRule[];
}

export interface CiCheckResult {
  clean: boolean;
  violations: ReturnType<typeof scanDiffForViolations>;
}

/**
 * Run the anti-pattern check over the diff between two refs (typically the PR
 * base and head). Prints a report and returns whether the diff is clean.
 */
export async function runCiCheck(options: CiCheckOptions): Promise<CiCheckResult> {
  const {
    base,
    head = 'HEAD',
    dbPath,
    repoPath = process.cwd(),
    rules = CATEGORY_RULES,
  } = options;

  const strikes = await getAllStrikes(dbPath);
  const activeStrikes = strikes.filter((s) => !s.resolved);

  if (activeStrikes.length === 0) {
    console.log(chalk.green('✔ No active strikes to check against.'));
    return { clean: true, violations: [] };
  }

  const diff = await getRangeDiff(base, head, repoPath);
  const violations = scanDiffForViolations(diff, activeStrikes, rules);

  if (violations.length > 0) {
    printViolations(violations, `[STRIKE LOGGER] CI check failed (${base}...${head})`);
    console.log(chalk.gray('  • Fix the flagged lines, or mark the related strikes resolved.'));
    console.log(chalk.gray('  • Run "strike-logger list" to review active strikes.\n'));
    return { clean: false, violations };
  }

  console.log(chalk.green(`✔ No recurring anti-patterns found in ${base}...${head}.`));
  return { clean: true, violations };
}
